//package com.quagnitia.myposmate.arke;
//
//import android.content.ComponentName;
//import android.content.Context;
//import android.content.Intent;
//import android.content.ServiceConnection;
//import android.os.IBinder;
//import android.os.RemoteException;
//import android.util.Log;
//
//import com.arke.vas.IVASListener;
//import com.arke.vas.data.VASPayload;
//import com.quagnitia.myposmate.R;
//import com.quagnitia.myposmate.utils.OnTaskCompleted;
//
//import org.json.JSONObject;
//
///**
// * Created by test on 2018/3/13.
// */
//
//public class VASCallsSdkBusiness {
//
//    private static String TAG = "VASCallsSdkBusiness";
//
//    // The Java class generated by the AIDL file
//    // 由AIDL文件生成的Java类
//    private static IVASCallSdkInterface vasCallSdkInterface = null;
//    private Context context;
//
//    // Server connection status, false for unconnected, true for connection
//    // 服务端连接状况，false为未连接，true为连接中
//    private boolean boundStatus = false;
//
//    public VASCallsSdkBusiness(Context context) {
//        this.context = context;
//    }
//
//    /**
//     * Do transaction
//     * 做交易
//     *
//     * @param interfaceId
//     */
//    OnTaskCompleted listener1;
//    public void doTransaction(final String interfaceId, JSONObject jsonObject, OnTaskCompleted listener1) {
//        this.listener1=listener1;
//
//        new Thread() {
//            @Override
//            public void run() {
//                try {
//                    Log.i(TAG, "[" + interfaceId + "]");
//                    bindServiceUntilConnect();
//
//
//                    String sendData = jsonObject.toString();//((DashboardActivity) context).getRequestData();
//                    if (interfaceId.equals("SALE")){//(TransactionNames.SALE_BY_SDK.name().equals(interfaceId)) {
//                        vasCallSdkInterface.sale(new VASPayload(sendData), listener);
//                    }
//                    else if(interfaceId.equals("COUPON_SALE"))
//                    {
//                        vasCallSdkInterface.sale(new VASPayload(sendData), listener);
//                    }
//
//
//                } catch (Exception e) {
//                    e.printStackTrace();
//                }
//            }
//        }.start();
//    }
//
//
//    /**
//     * Connect to the server
//     * <p>
//     * 与服务端建立连接
//     */
//    private void bindService() {
//        Intent intent = new Intent();
//        intent.setAction("com.arke.sdk.vas");
//        intent.setPackage("com.arke.sdk.demo");//cn.boc.shandong.ist//com.arke
//        context.bindService(intent, serviceConnection, Context.BIND_AUTO_CREATE);
//    }
//
//
//    /**
//     * Connect the service until the connection is successful
//     * <p>
//     * 连接服务，直到连接成功
//     */
//    private void bindServiceUntilConnect() {
//        try {
//            Log.i(TAG, context.getString(R.string.unbound_service_binding_service));
//            bindService();
//
//            while (vasCallSdkInterface == null) {
//                Thread.sleep(300);
//            }
//            Log.i(TAG, context.getString(R.string.connect_server_successfully));
//        } catch (InterruptedException e) {
//            e.printStackTrace();
//        }
//    }
//
//
//    /**
//     * Disconnect
//     * <p>
//     * 断开连接
//     *
//     * @param responseData
//     */
//    private void disconnect(String... responseData) {
//        Log.i(TAG, "disconnect()");
//        if (responseData != null && responseData.length > 0) {
//            Log.i(TAG, "onComplete,transaction end, responseData:" + responseData[0]);
//            try
//            {
//                Log.v("Response: Arke",responseData[0]);
//                listener1.onTaskCompleted(responseData[0],"Arke");
//            }
//            catch (Exception e)
//            {
//                e.printStackTrace();
//            }
//        }
//
//        context.unbindService(serviceConnection);
//        vasCallSdkInterface = null;
//        boundStatus = false;
//    }
//
//
//    private ServiceConnection serviceConnection = new ServiceConnection() {
//        @Override
//        public void onServiceConnected(ComponentName name, IBinder service) {
//            Log.i(TAG, "服务连接成功 onServiceConnected");
//            vasCallSdkInterface = IVASCallSdkInterface.Stub.asInterface(service);
//        }
//
//        @Override
//        public void onServiceDisconnected(ComponentName name) {
//            vasCallSdkInterface = null;
//        }
//    };
//
//    private IVASListener listener = new IVASListener.Stub() {
//        @Override
//        public void onStart() throws RemoteException {
//            Log.i(TAG, "onStart,begin transaction");
//        }
//
//        @Override
//        public void onNext(VASPayload vasPayload) throws RemoteException {
//            Log.i(TAG, " onNext,Transaction process information：" + vasPayload.toString());
//        }
//
//
//        @Override
//        public void onComplete(VASPayload responseData) throws RemoteException {
//            Log.i(TAG, " onComplete,Information returned at the end of the transaction：" + responseData);
//            disconnect(responseData == null ? "" : responseData.getBody());
//        }
//    };
//}
